matrix:
    include:
        - os: linux
          language: python
          python: 2.7
          env: TRAVIS_NODE_VERSION="6"
        - os: linux
          language: python
          python: 3.3
          env: TRAVIS_NODE_VERSION="8"
        - os: linux
          language: python
          python: 3.4
          env: TRAVIS_NODE_VERSION="8"
        - os: linux
          language: python
          python: 3.5
          env: TRAVIS_NODE_VERSION="9"
        - os: linux
          language: python
          python: 3.6
          env: TRAVIS_NODE_VERSION="9"
        - os: osx
          language: c
          # python: 3.4
          env: TRAVIS_NODE_VERSION="8"
        - os: osx
          language: c
          # python: 3.4
          env: TRAVIS_NODE_VERSION="9"

node_js:
  - 'node'

env:
  - TRAVIS_NODE_VERSION="6"

before_install: |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update
    brew upgrade python
  fi

install: |
  rm -rf ~/.nvm
  git clone https://github.com/creationix/nvm.git ~/.nvm
  (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  source ~/.nvm/nvm.sh
  nvm install $TRAVIS_NODE_VERSION
  npm install

script: "./build ci"
